version: "3"
services:
  db:
    container_name: db
    image: mysql:8.0
    command: "--innodb_use_native_aio=0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: app
      MYSQL_PASSWORD: 123
    ports:
      - "3308:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d/:ro
      - ./db/data:/var/lib/mysql
